### ISSUE TITLE
What does mpd_watch ...

### ISSUE THREAD

**Issue by bonelifer** [jmechnich/mpd-scripts#1]
What does [mpd_watch](https://github.com/jmechnich/mpd-scripts/blob/master/mpd_watch) do that's different from the mpd.socket service that comes with MPD? Maybe I'm just not understanding.

**Comment by jmechnich** [comment]
mpd_watch checks if a client connects to the http port for streaming and starts playback. If the last client disconnects it pauses playback. mpd will be running all the time and e.g. the playlist can be manipulated independently.
To my knowledge, mpd.socket will start mpd.service on demand when a **control** client connects (i.e. on TCP port 6600).

It might very well be possible that with additional configuration I could replicate similar functionality with systemd tools. Back in the day when this code was originally written this option simply did not exist.

**Comment by bonelifer** [comment]
Thanks for answering. Just scouring the web looking for interesting mpd related scripts. Now if only I could find a working lastfm script to use from keyboard shortcuts. everything I find is either no longer compilable or is no longer compatible with last.fm anymore.  And creating a working rest call using the API is outside my abilities.

**Comment by jmechnich** [comment]
What exactly do you want to do in the context of last.fm? For scrobbling played songs I am using the builtin feature of cantata. If you are not using a GUI client, tools like mpdscribble might (still) do the job. The script mpd_dynamic in this repo should be able to retrieve suggestions for songs from last.fm...but to be honest I have not used it in a long time in that way (just randomly adding songs from my collection).

**Comment by bonelifer** [comment]
I already have a script to get random, related artists to the current playing song. I was looking for a way to love/unlove the current artist/song.  I found an example on PyLast's github readme for doing this. So I've got that covered now. Thanks for the reply. Sorry for not being more clear. I thought I had mentioned that but you know brain to typing can sometimes lose half the info. LOL.
